name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: When I try to...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: I expected to see...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Instead, I saw...
    validations:
      required: true

  - type: input
    id: icon
    attributes:
      label: Icon ID (if applicable)
      description: Which icon(s) are affected?
      placeholder: e.g., react, nodejs, python

  - type: textarea
    id: url
    attributes:
      label: URL
      description: The full URL you were using when the issue occurred
      placeholder: https://techbadges.santosr.xyz/icons?i=...

  - type: textarea
    id: logs
    attributes:
      label: Logs or Error Messages
      description: Please copy and paste any relevant log output or error messages
      render: shell

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem

  - type: dropdown
    id: browser
    attributes:
      label: Browser (if applicable)
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here

