/**
 * Icon category definitions
 *
 * Categories help organize icons and enable filtering in the API.
 */

export type IconCategory =
  | 'language'
  | 'framework'
  | 'library'
  | 'database'
  | 'cloud'
  | 'devops'
  | 'tool'
  | 'ide'
  | 'os'
  | 'design'
  | 'game'
  | 'social'
  | 'other';

/**
 * Map of icon IDs to their categories
 * Icons not listed here default to 'other'
 */
export const ICON_CATEGORIES: Record<string, IconCategory> = {
  // Languages
  javascript: 'language',
  typescript: 'language',
  python: 'language',
  java: 'language',
  kotlin: 'language',
  swift: 'language',
  go: 'language',
  rust: 'language',
  cpp: 'language',
  c: 'language',
  cs: 'language',
  php: 'language',
  ruby: 'language',
  perl: 'language',
  lua: 'language',
  r: 'language',
  scala: 'language',
  elixir: 'language',
  clojure: 'language',
  haskell: 'language',
  dart: 'language',
  zig: 'language',
  nim: 'language',
  crystal: 'language',
  julia: 'language',
  fortran: 'language',
  cobol: 'language',
  matlab: 'language',
  octave: 'language',
  solidity: 'language',
  assembly: 'language',
  bash: 'language',
  powershell: 'language',
  html: 'language',
  css: 'language',
  sass: 'language',
  less: 'language',
  markdown: 'language',
  latex: 'language',
  graphql: 'language',
  wasm: 'language',
  v: 'language',
  d: 'language',
  ocaml: 'language',
  fsharp: 'language',
  gleam: 'language',
  raku: 'language',
  coffeescript: 'language',
  purescript: 'language',
  elm: 'language',
  nix: 'language',

  // Frontend Frameworks
  react: 'framework',
  vue: 'framework',
  angular: 'framework',
  svelte: 'framework',
  nextjs: 'framework',
  nuxtjs: 'framework',
  gatsby: 'framework',
  remix: 'framework',
  astro: 'framework',
  solidjs: 'framework',
  qwik: 'framework',
  lit: 'framework',
  preact: 'framework',
  alpinejs: 'framework',
  htmx: 'framework',
  ember: 'framework',

  // Backend Frameworks
  nodejs: 'framework',
  express: 'framework',
  nestjs: 'framework',
  fastify: 'framework',
  hono: 'framework',
  elysia: 'framework',
  django: 'framework',
  flask: 'framework',
  fastapi: 'framework',
  spring: 'framework',
  rails: 'framework',
  laravel: 'framework',
  symfony: 'framework',
  dotnet: 'framework',
  phoenix: 'framework',
  actix: 'framework',
  rocket: 'framework',
  gin: 'framework',
  fiber: 'framework',
  echo: 'framework',
  ktor: 'framework',

  // Mobile
  flutter: 'framework',
  reactnative: 'framework',
  ionic: 'framework',
  capacitor: 'framework',
  tauri: 'framework',
  electron: 'framework',

  // Libraries
  redux: 'library',
  mobx: 'library',
  zustand: 'library',
  jquery: 'library',
  lodash: 'library',
  rxjs: 'library',
  threejs: 'library',
  d3: 'library',
  tensorflow: 'library',
  pytorch: 'library',
  opencv: 'library',
  sklearn: 'library',
  pandas: 'library',
  numpy: 'library',
  babel: 'library',
  webpack: 'library',
  vite: 'library',
  rollup: 'library',
  esbuild: 'library',
  swc: 'library',
  tailwind: 'library',
  bootstrap: 'library',
  materialui: 'library',
  styledcomponents: 'library',
  emotion: 'library',
  prisma: 'library',
  sequelize: 'library',
  typeorm: 'library',
  drizzle: 'library',
  jest: 'library',
  vitest: 'library',
  cypress: 'library',
  playwright: 'library',
  selenium: 'library',
  storybook: 'library',

  // Databases
  mysql: 'database',
  postgres: 'database',
  mongodb: 'database',
  redis: 'database',
  sqlite: 'database',
  mariadb: 'database',
  oracle: 'database',
  cassandra: 'database',
  dynamodb: 'database',
  firebase: 'database',
  supabase: 'database',
  planetscale: 'database',
  cockroachdb: 'database',
  neo4j: 'database',
  elasticsearch: 'database',
  influxdb: 'database',
  couchdb: 'database',

  // Cloud & Hosting
  aws: 'cloud',
  azure: 'cloud',
  gcp: 'cloud',
  cloudflare: 'cloud',
  vercel: 'cloud',
  netlify: 'cloud',
  heroku: 'cloud',
  digitalocean: 'cloud',
  linode: 'cloud',
  vultr: 'cloud',
  railway: 'cloud',
  render: 'cloud',
  fly: 'cloud',

  // DevOps & CI/CD
  docker: 'devops',
  kubernetes: 'devops',
  terraform: 'devops',
  ansible: 'devops',
  jenkins: 'devops',
  githubactions: 'devops',
  gitlab: 'devops',
  bitbucket: 'devops',
  circleci: 'devops',
  travisci: 'devops',
  prometheus: 'devops',
  grafana: 'devops',
  nginx: 'devops',
  apache: 'devops',
  caddy: 'devops',
  kafka: 'devops',
  rabbitmq: 'devops',
  helm: 'devops',
  vault: 'devops',
  consul: 'devops',

  // Developer Tools
  git: 'tool',
  github: 'tool',
  npm: 'tool',
  pnpm: 'tool',
  yarn: 'tool',
  bun: 'tool',
  deno: 'tool',
  postman: 'tool',
  insomnia: 'tool',
  curl: 'tool',
  regex: 'tool',
  cmake: 'tool',
  gradle: 'tool',
  maven: 'tool',
  sentry: 'tool',
  datadog: 'tool',

  // IDEs & Editors
  vscode: 'ide',
  vim: 'ide',
  neovim: 'ide',
  emacs: 'ide',
  idea: 'ide',
  webstorm: 'ide',
  pycharm: 'ide',
  phpstorm: 'ide',
  goland: 'ide',
  rider: 'ide',
  clion: 'ide',
  rubymine: 'ide',
  datagrip: 'ide',
  androidstudio: 'ide',
  xcode: 'ide',
  eclipse: 'ide',
  atom: 'ide',
  sublime: 'ide',
  notepadplusplus: 'ide',
  cursor: 'ide',
  zed: 'ide',

  // Operating Systems
  linux: 'os',
  ubuntu: 'os',
  debian: 'os',
  fedora: 'os',
  arch: 'os',
  redhat: 'os',
  mint: 'os',
  kali: 'os',
  alpine: 'os',
  windows: 'os',
  apple: 'os',
  android: 'os',
  raspberrypi: 'os',
  plan9: 'os',
  bsd: 'os',

  // Design Tools
  figma: 'design',
  sketch: 'design',
  xd: 'design',
  photoshop: 'design',
  illustrator: 'design',
  aftereffects: 'design',
  premiere: 'design',
  blender: 'design',
  inkscape: 'design',
  gimp: 'design',
  canva: 'design',
  framer: 'design',
  invision: 'design',
  zeplin: 'design',

  // Game Development
  unity: 'game',
  unreal: 'game',
  godot: 'game',
  gamemaker: 'game',
  roblox: 'game',
  construct: 'game',
  phaser: 'game',
  pixi: 'game',
  bevy: 'game',
  monogame: 'game',

  // Social & Communication
  discord: 'social',
  slack: 'social',
  twitter: 'social',
  linkedin: 'social',
  stackoverflow: 'social',
  devto: 'social',
  medium: 'social',
  hashnode: 'social',
  mastodon: 'social',
  bluesky: 'social',
  threads: 'social',
  instagram: 'social',
  youtube: 'social',
  twitch: 'social',
  tiktok: 'social',
  reddit: 'social',
  gmail: 'social',
  notion: 'social',
  obsidian: 'social',
};

/**
 * Get category for an icon ID
 */
export function getIconCategory(iconId: string): IconCategory {
  return ICON_CATEGORIES[iconId.toLowerCase()] ?? 'other';
}
